#include "bt_unit_test_gatt.h"

#define BT_ADDR_LENGTH 18

typedef enum
{
	BT_GATT_TEST_UNRECOVERABLE = 1,
	BT_GATT_TEST_CUSTOM_INITIALIZATION,
	BT_GATT_TEST_CUSTOM_INITIALIZED,
	BT_GATT_TEST_CUSTOM_SERVER_INITIALIZING,
	BT_GATT_TEST_CUSTOM_SERVER_INITIALIZED,
	BT_UNIT_TEST_TABLE_FINISH = 0xFF,
} custom_test_gatt_state_e;

static char remote_addr[BT_ADDR_LENGTH] = "00:11:22:33:44:55";